name : setup and Build a Node App

on :
    push:
       branches:
         - development

    pull_request: 
        branches:
          - development


jobs:
    ci:
       name: build
       runs-on: ubuntu-latest
    
       steps:
         - name: checkout
           uses: actions/checkout@v4

         - name: NodeSetUp
           uses: actions/setup-node@v4
           with: 
            node-version: 22

         - name: Install Dependencies
           run: npm ci
           
         - name: build
           run: npm run build

         



     

	  



          