name: CI - Build and Promote

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

permissions:
  contents: write

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  promote:
    name: Promote Development to Main
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Development
      uses: actions/checkout@v4
      with:
        ref: development
        fetch-depth: 0

    - name: Promote to Main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git fetch origin main

        git checkout main

        git merge development --ff-only

        git push origin main

  deploy:
    name: Deploy to EC2
    needs: promote
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying application..."

            cd /home/ubuntu/my-node-app

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Building application..."
            npm run build

            echo "Restarting application..."
            pm2 restart my-node-app || pm2 start npm --name "my-node-app" -- start